# Site settings
title: Brasserie La DifferAnce
email: differancesaintthibery@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: '/'
url: 'https://differancesaintthibery.fr'

instagram_username: brasserie_la_differance
facebook_username: Brasserie-La-DifferAnce-100077345691675

# Build settings
markdown: kramdown
